// Marcello — Preloaded Fine Art Museum Database
const MUSEUMS = [
  // === NORTH AMERICA ===
  // United States
  { id: "met", name: "The Metropolitan Museum of Art", city: "New York", country: "United States", continent: "North America", lat: 40.7794, lng: -73.9632, type: "Encyclopedic", description: "One of the world's largest and most comprehensive art museums, with over 5,000 years of art from around the globe.", website: "https://www.metmuseum.org" },
  { id: "moma", name: "Museum of Modern Art (MoMA)", city: "New York", country: "United States", continent: "North America", lat: 40.7614, lng: -73.9776, type: "Modern Art", description: "A leading museum of modern and contemporary art, home to iconic works by Van Gogh, Picasso, and Warhol.", website: "https://www.moma.org" },
  { id: "guggenheim-nyc", name: "Solomon R. Guggenheim Museum", city: "New York", country: "United States", continent: "North America", lat: 40.7830, lng: -73.9590, type: "Modern Art", description: "Frank Lloyd Wright's iconic spiral building housing an impressive collection of Impressionist and modern art.", website: "https://www.guggenheim.org" },
  { id: "whitney", name: "Whitney Museum of American Art", city: "New York", country: "United States", continent: "North America", lat: 40.7396, lng: -74.0089, type: "Contemporary", description: "Dedicated to 20th- and 21st-century American art, housed in a striking Renzo Piano building.", website: "https://whitney.org" },
  { id: "frick", name: "The Frick Collection", city: "New York", country: "United States", continent: "North America", lat: 40.7711, lng: -73.9673, type: "Fine Art", description: "An intimate museum featuring Old Masters and European fine art in a Gilded Age mansion.", website: "https://www.frick.org" },
  { id: "neue-galerie", name: "Neue Galerie New York", city: "New York", country: "United States", continent: "North America", lat: 40.7813, lng: -73.9628, type: "Fine Art", description: "Dedicated to early 20th-century German and Austrian art and design, home to Klimt's Portrait of Adele Bloch-Bauer I.", website: "https://www.neuegalerie.org" },
  { id: "brooklyn-museum", name: "Brooklyn Museum", city: "New York", country: "United States", continent: "North America", lat: 40.6712, lng: -73.9636, type: "Encyclopedic", description: "One of the oldest and largest art museums in the US with an encyclopedic collection spanning Egyptian to contemporary.", website: "https://www.brooklynmuseum.org" },
  { id: "art-institute-chicago", name: "Art Institute of Chicago", city: "Chicago", country: "United States", continent: "North America", lat: 41.8796, lng: -87.6237, type: "Encyclopedic", description: "Home to one of the world's finest collections of Impressionist and Post-Impressionist paintings, including A Sunday on La Grande Jatte.", website: "https://www.artic.edu" },
  { id: "national-gallery-dc", name: "National Gallery of Art", city: "Washington, D.C.", country: "United States", continent: "North America", lat: 38.8913, lng: -77.0200, type: "Fine Art", description: "Houses one of the finest collections in the world spanning European and American art from the Middle Ages to present.", website: "https://www.nga.gov" },
  { id: "hirshhorn", name: "Hirshhorn Museum and Sculpture Garden", city: "Washington, D.C.", country: "United States", continent: "North America", lat: 38.8882, lng: -77.0230, type: "Contemporary", description: "The Smithsonian's modern and contemporary art museum, known for its cylindrical building and outdoor sculpture garden.", website: "https://hirshhorn.si.edu" },
  { id: "phillips-collection", name: "The Phillips Collection", city: "Washington, D.C.", country: "United States", continent: "North America", lat: 38.9116, lng: -77.0469, type: "Modern Art", description: "America's first museum of modern art, featuring Renoir's Luncheon of the Boating Party.", website: "https://www.phillipscollection.org" },
  { id: "getty-center", name: "The J. Paul Getty Museum", city: "Los Angeles", country: "United States", continent: "North America", lat: 34.0780, lng: -118.4741, type: "Fine Art", description: "Perched atop a hill with stunning architecture by Richard Meier, housing European paintings, drawings, and photographs.", website: "https://www.getty.edu" },
  { id: "lacma", name: "Los Angeles County Museum of Art (LACMA)", city: "Los Angeles", country: "United States", continent: "North America", lat: 34.0639, lng: -118.3592, type: "Encyclopedic", description: "The largest art museum in the western US, spanning thousands of years of art from across the globe.", website: "https://www.lacma.org" },
  { id: "moca-la", name: "Museum of Contemporary Art (MOCA)", city: "Los Angeles", country: "United States", continent: "North America", lat: 34.0531, lng: -118.2505, type: "Contemporary", description: "LA's premier contemporary art museum dedicated to art created since 1940.", website: "https://www.moca.org" },
  { id: "broad", name: "The Broad", city: "Los Angeles", country: "United States", continent: "North America", lat: 34.0545, lng: -118.2509, type: "Contemporary", description: "A contemporary art museum featuring the Broad collection of postwar and contemporary art in a striking honeycomb building.", website: "https://www.thebroad.org" },
  { id: "sfmoma", name: "San Francisco Museum of Modern Art (SFMOMA)", city: "San Francisco", country: "United States", continent: "North America", lat: 37.7857, lng: -122.4011, type: "Modern Art", description: "One of the largest modern and contemporary art museums in the US with a renowned photography collection.", website: "https://www.sfmoma.org" },
  { id: "de-young", name: "de Young Museum", city: "San Francisco", country: "United States", continent: "North America", lat: 37.7716, lng: -122.4686, type: "Fine Art", description: "Located in Golden Gate Park, showcasing American art, international textiles, and African and Oceanic art.", website: "https://www.famsf.org/deyoung" },
  { id: "legion-honor", name: "Legion of Honor", city: "San Francisco", country: "United States", continent: "North America", lat: 37.7847, lng: -122.5010, type: "Fine Art", description: "A Beaux-Arts museum in Lincoln Park housing 4,000 years of European art with stunning views of the Golden Gate Bridge.", website: "https://www.famsf.org/legion-of-honor" },
  { id: "mfa-boston", name: "Museum of Fine Arts, Boston", city: "Boston", country: "United States", continent: "North America", lat: 42.3394, lng: -71.0940, type: "Encyclopedic", description: "One of the most comprehensive art museums in the world with exceptional collections of Asian, Egyptian, and Impressionist art.", website: "https://www.mfa.org" },
  { id: "isabella-stewart-gardner", name: "Isabella Stewart Gardner Museum", city: "Boston", country: "United States", continent: "North America", lat: 42.3382, lng: -71.0990, type: "Fine Art", description: "A Venetian-style palazzo housing an eclectic collection arranged exactly as Gardner intended, site of a famous art heist.", website: "https://www.gardnermuseum.org" },
  { id: "pma-philadelphia", name: "Philadelphia Museum of Art", city: "Philadelphia", country: "United States", continent: "North America", lat: 39.9656, lng: -75.1810, type: "Encyclopedic", description: "One of America's largest art museums, famous for its Rocky steps and outstanding collections across all periods.", website: "https://www.philamuseum.org" },
  { id: "barnes", name: "The Barnes Foundation", city: "Philadelphia", country: "United States", continent: "North America", lat: 39.9606, lng: -75.1728, type: "Fine Art", description: "Houses one of the world's greatest collections of Impressionist, Post-Impressionist, and early Modern paintings.", website: "https://www.barnesfoundation.org" },
  { id: "cleveland-museum", name: "Cleveland Museum of Art", city: "Cleveland", country: "United States", continent: "North America", lat: 41.5091, lng: -81.6120, type: "Encyclopedic", description: "A world-class encyclopedic museum known for its Asian and medieval European art collections, free to the public.", website: "https://www.clevelandart.org" },
  { id: "dia", name: "Detroit Institute of Arts", city: "Detroit", country: "United States", continent: "North America", lat: 42.3594, lng: -83.0645, type: "Encyclopedic", description: "Home to Diego Rivera's Detroit Industry Murals and over 65,000 artworks spanning global cultures.", website: "https://www.dia.org" },
  { id: "nelson-atkins", name: "Nelson-Atkins Museum of Art", city: "Kansas City", country: "United States", continent: "North America", lat: 39.0453, lng: -94.5810, type: "Encyclopedic", description: "Renowned for its Asian art collection and the iconic Shuttlecocks sculpture on the lawn.", website: "https://www.nelson-atkins.org" },
  { id: "mfah", name: "Museum of Fine Arts, Houston", city: "Houston", country: "United States", continent: "North America", lat: 29.7260, lng: -95.3909, type: "Encyclopedic", description: "One of the largest art museums in the US with an encyclopedic collection and stunning campus.", website: "https://www.mfah.org" },
  { id: "menil", name: "The Menil Collection", city: "Houston", country: "United States", continent: "North America", lat: 29.7372, lng: -95.3984, type: "Fine Art", description: "A free museum housing a major private collection spanning antiquity to contemporary, designed by Renzo Piano.", website: "https://www.menil.org" },
  { id: "minneapolis-institute", name: "Minneapolis Institute of Art", city: "Minneapolis", country: "United States", continent: "North America", lat: 44.9585, lng: -93.2732, type: "Encyclopedic", description: "Home to more than 90,000 works spanning 5,000 years, free and open to all.", website: "https://new.artsmia.org" },
  { id: "walker", name: "Walker Art Center", city: "Minneapolis", country: "United States", continent: "North America", lat: 44.9688, lng: -93.2888, type: "Contemporary", description: "One of the most celebrated contemporary art centers in the US with the iconic Minneapolis Sculpture Garden.", website: "https://walkerart.org" },
  { id: "high-museum", name: "High Museum of Art", city: "Atlanta", country: "United States", continent: "North America", lat: 33.7901, lng: -84.3856, type: "Fine Art", description: "The leading art museum in the southeastern US with a strong collection of American, European, and African art.", website: "https://www.high.org" },
  { id: "national-gallery-canada", name: "National Gallery of Canada", city: "Ottawa", country: "Canada", continent: "North America", lat: 45.4295, lng: -75.6989, type: "Fine Art", description: "Canada's premier art gallery featuring an extensive collection of Canadian and European art in a striking glass building.", website: "https://www.gallery.ca" },
  { id: "ago", name: "Art Gallery of Ontario", city: "Toronto", country: "Canada", continent: "North America", lat: 43.6536, lng: -79.3925, type: "Encyclopedic", description: "One of the largest art museums in North America, renovated by Frank Gehry, with strong Canadian and European collections.", website: "https://ago.ca" },
  { id: "museo-nacional-arte", name: "Museo Nacional de Arte (MUNAL)", city: "Mexico City", country: "Mexico", continent: "North America", lat: 19.4361, lng: -99.1400, type: "Fine Art", description: "Mexico's national art museum showcasing five centuries of Mexican art from the 16th century to the mid-20th century.", website: "https://www.munal.mx" },
  { id: "museo-tamayo", name: "Museo Tamayo Arte Contemporáneo", city: "Mexico City", country: "Mexico", continent: "North America", lat: 19.4262, lng: -99.1816, type: "Contemporary", description: "A contemporary art museum founded by Rufino Tamayo, set in Chapultepec Park.", website: "https://www.museotamayo.org" },
  { id: "museo-soumaya", name: "Museo Soumaya", city: "Mexico City", country: "Mexico", continent: "North America", lat: 19.4403, lng: -99.2056, type: "Fine Art", description: "A free museum in a striking aluminum-tiled building housing European Old Masters and Rodin sculptures.", website: "https://www.museosoumaya.org" },

  // === EUROPE ===
  // France
  { id: "louvre", name: "Musée du Louvre", city: "Paris", country: "France", continent: "Europe", lat: 48.8606, lng: 2.3376, type: "Encyclopedic", description: "The world's most visited museum and home to the Mona Lisa, Venus de Milo, and thousands of masterworks spanning millennia.", website: "https://www.louvre.fr" },
  { id: "musee-orsay", name: "Musée d'Orsay", city: "Paris", country: "France", continent: "Europe", lat: 48.8600, lng: 2.3266, type: "Fine Art", description: "Housed in a stunning Beaux-Arts railway station, home to the world's greatest collection of Impressionist and Post-Impressionist art.", website: "https://www.musee-orsay.fr" },
  { id: "centre-pompidou", name: "Centre Pompidou", city: "Paris", country: "France", continent: "Europe", lat: 48.8607, lng: 2.3523, type: "Modern Art", description: "Europe's largest modern art collection in an iconic inside-out building by Renzo Piano and Richard Rogers.", website: "https://www.centrepompidou.fr" },
  { id: "orangerie", name: "Musée de l'Orangerie", city: "Paris", country: "France", continent: "Europe", lat: 48.8638, lng: 2.3226, type: "Fine Art", description: "Famous for Monet's monumental Water Lilies murals and an impressive collection of Impressionist and Post-Impressionist paintings.", website: "https://www.musee-orangerie.fr" },
  { id: "rodin-museum-paris", name: "Musée Rodin", city: "Paris", country: "France", continent: "Europe", lat: 48.8554, lng: 2.3160, type: "Fine Art", description: "Dedicated to the works of sculptor Auguste Rodin, including The Thinker, set in a beautiful 18th-century mansion.", website: "https://www.musee-rodin.fr" },
  { id: "petit-palais", name: "Petit Palais", city: "Paris", country: "France", continent: "Europe", lat: 48.8660, lng: 2.3140, type: "Fine Art", description: "Paris's museum of fine arts with a free permanent collection spanning antiquity to 1900 in a stunning Beaux-Arts building.", website: "https://www.petitpalais.paris.fr" },
  { id: "musee-picasso-paris", name: "Musée Picasso", city: "Paris", country: "France", continent: "Europe", lat: 48.8596, lng: 2.3625, type: "Modern Art", description: "The world's largest collection of Picasso's works housed in a beautiful 17th-century mansion in the Marais.", website: "https://www.museepicassoparis.fr" },
  { id: "quai-branly", name: "Musée du quai Branly – Jacques Chirac", city: "Paris", country: "France", continent: "Europe", lat: 48.8611, lng: 2.2977, type: "Encyclopedic", description: "Showcasing indigenous art and cultures from Africa, Asia, Oceania, and the Americas in a Jean Nouvel building.", website: "https://www.quaibranly.fr" },
  { id: "lyon-mba", name: "Musée des Beaux-Arts de Lyon", city: "Lyon", country: "France", continent: "Europe", lat: 45.7670, lng: 4.8338, type: "Fine Art", description: "One of the largest fine arts museums in France, housed in a 17th-century former Benedictine convent.", website: "https://www.mba-lyon.fr" },

  // United Kingdom
  { id: "national-gallery-london", name: "The National Gallery", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5089, lng: -0.1283, type: "Fine Art", description: "Home to over 2,300 paintings from the 13th to 19th centuries, including works by da Vinci, Van Gogh, and Turner.", website: "https://www.nationalgallery.org.uk" },
  { id: "tate-modern", name: "Tate Modern", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5076, lng: -0.0994, type: "Modern Art", description: "Britain's national gallery of modern and contemporary art, housed in a converted power station on the Thames.", website: "https://www.tate.org.uk/visit/tate-modern" },
  { id: "tate-britain", name: "Tate Britain", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.4910, lng: -0.1279, type: "Fine Art", description: "The world's greatest collection of British art from 1500 to today, home to the annual Turner Prize exhibition.", website: "https://www.tate.org.uk/visit/tate-britain" },
  { id: "british-museum", name: "British Museum", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5194, lng: -0.1270, type: "Encyclopedic", description: "A vast encyclopedic museum spanning two million years of human history, including the Rosetta Stone and Parthenon sculptures.", website: "https://www.britishmuseum.org" },
  { id: "va", name: "Victoria and Albert Museum", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.4966, lng: -0.1722, type: "Fine Art", description: "The world's largest museum of applied and decorative arts and design, spanning 5,000 years.", website: "https://www.vam.ac.uk" },
  { id: "courtauld", name: "The Courtauld Gallery", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5115, lng: -0.1174, type: "Fine Art", description: "An intimate gallery with a world-famous collection of Impressionist and Post-Impressionist paintings.", website: "https://courtauld.ac.uk/gallery" },
  { id: "national-portrait-london", name: "National Portrait Gallery", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5094, lng: -0.1281, type: "Fine Art", description: "Houses portraits of historically important and famous British people from the Tudor era to present.", website: "https://www.npg.org.uk" },
  { id: "wallace-collection", name: "The Wallace Collection", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5177, lng: -0.1530, type: "Fine Art", description: "An outstanding collection of fine and decorative arts in an historic London townhouse, featuring Frans Hals's Laughing Cavalier.", website: "https://www.wallacecollection.org" },
  { id: "national-galleries-scotland", name: "Scottish National Gallery", city: "Edinburgh", country: "United Kingdom", continent: "Europe", lat: 55.9509, lng: -3.1956, type: "Fine Art", description: "Scotland's national collection of fine art from the Renaissance to Post-Impressionism.", website: "https://www.nationalgalleries.org" },

  // Italy
  { id: "uffizi", name: "Uffizi Gallery", city: "Florence", country: "Italy", continent: "Europe", lat: 43.7677, lng: 11.2553, type: "Fine Art", description: "One of the world's oldest and most famous art museums, housing masterpieces by Botticelli, Leonardo, and Michelangelo.", website: "https://www.uffizi.it" },
  { id: "palazzo-pitti", name: "Palazzo Pitti", city: "Florence", country: "Italy", continent: "Europe", lat: 43.7651, lng: 11.2501, type: "Fine Art", description: "A vast Renaissance palace housing several museums including the Palatine Gallery with works by Raphael and Titian.", website: "https://www.uffizi.it/palazzo-pitti" },
  { id: "accademia-florence", name: "Galleria dell'Accademia", city: "Florence", country: "Italy", continent: "Europe", lat: 43.7769, lng: 11.2588, type: "Fine Art", description: "Home to Michelangelo's iconic David and an impressive collection of Florentine paintings.", website: "https://www.galleriaaccademiafirenze.it" },
  { id: "vatican-museums", name: "Vatican Museums", city: "Vatican City", country: "Vatican City", continent: "Europe", lat: 41.9065, lng: 12.4536, type: "Encyclopedic", description: "A vast complex of museums and galleries including the Sistine Chapel with Michelangelo's legendary ceiling frescoes.", website: "https://www.museivaticani.va" },
  { id: "borghese", name: "Galleria Borghese", city: "Rome", country: "Italy", continent: "Europe", lat: 41.9142, lng: 12.4922, type: "Fine Art", description: "An exquisite collection of Bernini sculptures, Caravaggio paintings, and Renaissance masterworks in a beautiful villa.", website: "https://galleriaborghese.beniculturali.it" },
  { id: "palazzo-barberini", name: "Galleria Nazionale d'Arte Antica – Palazzo Barberini", city: "Rome", country: "Italy", continent: "Europe", lat: 41.9034, lng: 12.4897, type: "Fine Art", description: "Italian national gallery of ancient art featuring works from the 13th to 18th century in a Baroque palace.", website: "https://www.barberinicorsini.org" },
  { id: "venice-accademia", name: "Gallerie dell'Accademia", city: "Venice", country: "Italy", continent: "Europe", lat: 45.4314, lng: 12.3288, type: "Fine Art", description: "Venice's premier art museum with the world's finest collection of Venetian painting from the 14th to 18th century.", website: "https://www.gallerieaccademia.it" },
  { id: "peggy-guggenheim", name: "Peggy Guggenheim Collection", city: "Venice", country: "Italy", continent: "Europe", lat: 45.4310, lng: 12.3318, type: "Modern Art", description: "One of Europe's most important collections of early 20th-century art in a palazzo on the Grand Canal.", website: "https://www.guggenheim-venice.it" },
  { id: "pinacoteca-brera", name: "Pinacoteca di Brera", city: "Milan", country: "Italy", continent: "Europe", lat: 45.4720, lng: 9.1880, type: "Fine Art", description: "Milan's main public gallery for paintings, featuring Italian Renaissance masterpieces including Raphael's Marriage of the Virgin.", website: "https://pinacotecabrera.org" },
  { id: "capodimonte", name: "Museo di Capodimonte", city: "Naples", country: "Italy", continent: "Europe", lat: 40.8675, lng: 14.2503, type: "Fine Art", description: "Set in a Bourbon palace, housing one of Italy's richest art collections with works by Titian, Caravaggio, and El Greco.", website: "https://www.museocapodimonte.beniculturali.it" },

  // Spain
  { id: "prado", name: "Museo Nacional del Prado", city: "Madrid", country: "Spain", continent: "Europe", lat: 40.4138, lng: -3.6921, type: "Fine Art", description: "Spain's national art museum with an unrivaled collection of European art, especially Velázquez, Goya, and El Greco.", website: "https://www.museodelprado.es" },
  { id: "reina-sofia", name: "Museo Reina Sofía", city: "Madrid", country: "Spain", continent: "Europe", lat: 40.4087, lng: -3.6943, type: "Modern Art", description: "Spain's national museum of 20th-century art, home to Picasso's Guernica and works by Dalí and Miró.", website: "https://www.museoreinasofia.es" },
  { id: "thyssen", name: "Museo Nacional Thyssen-Bornemisza", city: "Madrid", country: "Spain", continent: "Europe", lat: 40.4160, lng: -3.6950, type: "Fine Art", description: "Completes Madrid's Golden Triangle of Art with a sweeping survey from medieval to pop art.", website: "https://www.museothyssen.org" },
  { id: "museu-picasso-barcelona", name: "Museu Picasso", city: "Barcelona", country: "Spain", continent: "Europe", lat: 41.3851, lng: 2.1808, type: "Modern Art", description: "Dedicated to the formative years and early works of Pablo Picasso in five adjoining medieval palaces.", website: "https://www.museupicasso.bcn.cat" },
  { id: "macba", name: "MACBA – Museu d'Art Contemporani", city: "Barcelona", country: "Spain", continent: "Europe", lat: 41.3835, lng: 2.1668, type: "Contemporary", description: "Barcelona's leading contemporary art museum in a striking white Richard Meier building.", website: "https://www.macba.cat" },
  { id: "guggenheim-bilbao", name: "Guggenheim Museum Bilbao", city: "Bilbao", country: "Spain", continent: "Europe", lat: 43.2687, lng: -2.9340, type: "Contemporary", description: "Frank Gehry's titanium-clad masterpiece that transformed Bilbao, housing major contemporary artworks.", website: "https://www.guggenheim-bilbao.eus" },

  // Netherlands
  { id: "rijksmuseum", name: "Rijksmuseum", city: "Amsterdam", country: "Netherlands", continent: "Europe", lat: 52.3600, lng: 4.8852, type: "Fine Art", description: "The Dutch national museum housing Rembrandt's Night Watch, Vermeer's Milkmaid, and 8,000 other masterpieces.", website: "https://www.rijksmuseum.nl" },
  { id: "van-gogh-museum", name: "Van Gogh Museum", city: "Amsterdam", country: "Netherlands", continent: "Europe", lat: 52.3584, lng: 4.8811, type: "Fine Art", description: "Houses the world's largest collection of Van Gogh's paintings and letters, tracing his artistic evolution.", website: "https://www.vangoghmuseum.nl" },
  { id: "stedelijk", name: "Stedelijk Museum Amsterdam", city: "Amsterdam", country: "Netherlands", continent: "Europe", lat: 52.3580, lng: 4.8798, type: "Modern Art", description: "Amsterdam's museum of modern and contemporary art and design, with works from 1870 to today.", website: "https://www.stedelijk.nl" },
  { id: "mauritshuis", name: "Mauritshuis", city: "The Hague", country: "Netherlands", continent: "Europe", lat: 52.0804, lng: 4.3142, type: "Fine Art", description: "An intimate royal picture gallery housing Vermeer's Girl with a Pearl Earring and other Dutch Golden Age masterpieces.", website: "https://www.mauritshuis.nl" },
  { id: "kroller-muller", name: "Kröller-Müller Museum", city: "Otterlo", country: "Netherlands", continent: "Europe", lat: 52.0967, lng: 5.8167, type: "Modern Art", description: "Set in a national park, housing the second-largest Van Gogh collection and a renowned sculpture garden.", website: "https://krollermuller.nl" },

  // Germany
  { id: "alte-pinakothek", name: "Alte Pinakothek", city: "Munich", country: "Germany", continent: "Europe", lat: 48.1483, lng: 11.5700, type: "Fine Art", description: "One of the oldest galleries in the world, with masterpieces of European painting from the 14th to 18th century.", website: "https://www.pinakothek.de/alte-pinakothek" },
  { id: "neue-pinakothek", name: "Neue Pinakothek", city: "Munich", country: "Germany", continent: "Europe", lat: 48.1494, lng: 11.5717, type: "Fine Art", description: "Dedicated to European art of the 18th and 19th centuries, from Rococo to Art Nouveau.", website: "https://www.pinakothek.de/neue-pinakothek" },
  { id: "pinakothek-moderne", name: "Pinakothek der Moderne", city: "Munich", country: "Germany", continent: "Europe", lat: 48.1472, lng: 11.5728, type: "Modern Art", description: "One of the world's largest museums for modern and contemporary art, design, works on paper, and architecture.", website: "https://www.pinakothek.de/pinakothek-der-moderne" },
  { id: "gemaldegalerie-berlin", name: "Gemäldegalerie", city: "Berlin", country: "Germany", continent: "Europe", lat: 52.5083, lng: 13.3650, type: "Fine Art", description: "One of the world's foremost collections of European paintings from the 13th to 18th century.", website: "https://www.smb.museum/en/museums-institutions/gemaeldegalerie" },
  { id: "pergamon", name: "Pergamon Museum", city: "Berlin", country: "Germany", continent: "Europe", lat: 52.5213, lng: 13.3969, type: "Encyclopedic", description: "Home to monumental archaeological reconstructions including the Ishtar Gate of Babylon.", website: "https://www.smb.museum/en/museums-institutions/pergamonmuseum" },
  { id: "hamburger-bahnhof", name: "Hamburger Bahnhof", city: "Berlin", country: "Germany", continent: "Europe", lat: 52.5284, lng: 13.3728, type: "Contemporary", description: "Berlin's main contemporary art museum in a former railway station, with works by Beuys, Warhol, and Kiefer.", website: "https://www.smb.museum/en/museums-institutions/hamburger-bahnhof" },
  { id: "staedel", name: "Städel Museum", city: "Frankfurt", country: "Germany", continent: "Europe", lat: 50.1048, lng: 8.6724, type: "Fine Art", description: "One of Germany's oldest and most important art museums spanning 700 years of European art.", website: "https://www.staedelmuseum.de" },
  { id: "zwinger-dresden", name: "Gemäldegalerie Alte Meister (Zwinger)", city: "Dresden", country: "Germany", continent: "Europe", lat: 51.0536, lng: 13.7343, type: "Fine Art", description: "Home to Raphael's Sistine Madonna and an outstanding collection of Old Master paintings in the stunning Zwinger palace.", website: "https://gemaeldegalerie.skd.museum" },

  // Austria
  { id: "kunsthistorisches", name: "Kunsthistorisches Museum", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.2034, lng: 16.3614, type: "Fine Art", description: "One of the world's foremost fine art museums with masterpieces by Bruegel, Vermeer, Raphael, and Caravaggio.", website: "https://www.khm.at" },
  { id: "belvedere", name: "Belvedere Museum", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.1915, lng: 16.3808, type: "Fine Art", description: "Home to Gustav Klimt's The Kiss and a superb collection of Austrian art in two Baroque palaces.", website: "https://www.belvedere.at" },
  { id: "leopold-museum", name: "Leopold Museum", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.2036, lng: 16.3578, type: "Modern Art", description: "Houses the world's largest collection of Egon Schiele works, plus Klimt, Kokoschka, and Viennese art.", website: "https://www.leopoldmuseum.org" },
  { id: "mumok", name: "mumok – Museum of Modern Art", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.2040, lng: 16.3567, type: "Modern Art", description: "Austria's largest museum of modern and contemporary art, from Expressionism to Pop Art and beyond.", website: "https://www.mumok.at" },
  { id: "albertina", name: "Albertina", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.2048, lng: 16.3680, type: "Fine Art", description: "Houses one of the largest and most important print rooms in the world, plus Monet to Picasso exhibitions.", website: "https://www.albertina.at" },

  // Switzerland
  { id: "kunstmuseum-basel", name: "Kunstmuseum Basel", city: "Basel", country: "Switzerland", continent: "Europe", lat: 47.5543, lng: 7.5930, type: "Fine Art", description: "The oldest public art collection in the world, featuring Holbein, Picasso, and a strong modern collection.", website: "https://www.kunstmuseumbasel.ch" },
  { id: "fondation-beyeler", name: "Fondation Beyeler", city: "Basel", country: "Switzerland", continent: "Europe", lat: 47.5905, lng: 7.5977, type: "Modern Art", description: "A world-class modern art collection in a stunning Renzo Piano building, featuring Monet, Picasso, and Rothko.", website: "https://www.fondationbeyeler.ch" },
  { id: "kunsthaus-zurich", name: "Kunsthaus Zürich", city: "Zurich", country: "Switzerland", continent: "Europe", lat: 47.3704, lng: 8.5483, type: "Fine Art", description: "Switzerland's most important art museum with significant Giacometti, Munch, and Impressionist holdings.", website: "https://www.kunsthaus.ch" },

  // Belgium
  { id: "royal-museums-brussels", name: "Royal Museums of Fine Arts of Belgium", city: "Brussels", country: "Belgium", continent: "Europe", lat: 50.8420, lng: 4.3577, type: "Fine Art", description: "A complex of six museums with exceptional Flemish and Belgian art including Bruegel, Rubens, and Magritte.", website: "https://www.fine-arts-museum.be" },
  { id: "magritte-museum", name: "Magritte Museum", city: "Brussels", country: "Belgium", continent: "Europe", lat: 50.8423, lng: 4.3580, type: "Modern Art", description: "The world's largest collection of works by surrealist René Magritte, with over 200 pieces.", website: "https://www.musee-magritte-museum.be" },

  // Russia
  { id: "hermitage", name: "State Hermitage Museum", city: "Saint Petersburg", country: "Russia", continent: "Europe", lat: 59.9398, lng: 30.3146, type: "Encyclopedic", description: "One of the world's largest and oldest museums, housed in the Winter Palace with over 3 million items.", website: "https://www.hermitagemuseum.org" },
  { id: "tretyakov", name: "Tretyakov Gallery", city: "Moscow", country: "Russia", continent: "Europe", lat: 55.7415, lng: 37.6208, type: "Fine Art", description: "Russia's foremost gallery of national art, housing the finest collection of Russian fine art in the world.", website: "https://www.tretyakovgallery.ru" },
  { id: "pushkin-museum", name: "Pushkin State Museum of Fine Arts", city: "Moscow", country: "Russia", continent: "Europe", lat: 55.7473, lng: 37.6050, type: "Fine Art", description: "Moscow's primary museum of European art with important Impressionist and Post-Impressionist collections.", website: "https://pushkinmuseum.art" },

  // Scandinavia
  { id: "national-museum-stockholm", name: "Nationalmuseum", city: "Stockholm", country: "Sweden", continent: "Europe", lat: 59.3281, lng: 18.0705, type: "Fine Art", description: "Sweden's premier museum of art and design with paintings, sculptures, and applied arts from the Renaissance to 1900.", website: "https://www.nationalmuseum.se" },
  { id: "moderna-museet", name: "Moderna Museet", city: "Stockholm", country: "Sweden", continent: "Europe", lat: 59.3261, lng: 18.0847, type: "Modern Art", description: "Sweden's leading museum of modern and contemporary art with works by Picasso, Dalí, and Matisse.", website: "https://www.modernamuseet.se" },
  { id: "national-museum-oslo", name: "The National Museum", city: "Oslo", country: "Norway", continent: "Europe", lat: 59.9091, lng: 10.7348, type: "Encyclopedic", description: "The largest art museum in Scandinavia, home to Munch's The Scream and extensive Nordic collections.", website: "https://www.nasjonalmuseet.no" },
  { id: "munch-museum", name: "MUNCH", city: "Oslo", country: "Norway", continent: "Europe", lat: 59.9063, lng: 10.7565, type: "Fine Art", description: "The world's largest collection of Edvard Munch's art in a striking new waterfront building.", website: "https://www.munchmuseet.no" },
  { id: "louisiana", name: "Louisiana Museum of Modern Art", city: "Humlebæk", country: "Denmark", continent: "Europe", lat: 55.9688, lng: 12.5427, type: "Modern Art", description: "One of Scandinavia's most visited museums, beautifully set on the coast with sculpture gardens and sea views.", website: "https://louisiana.dk" },
  { id: "smk", name: "SMK – National Gallery of Denmark", city: "Copenhagen", country: "Denmark", continent: "Europe", lat: 55.6888, lng: 12.5775, type: "Fine Art", description: "Denmark's largest art museum with Danish and international art spanning 700 years.", website: "https://www.smk.dk" },
  { id: "ateneum", name: "Ateneum Art Museum", city: "Helsinki", country: "Finland", continent: "Europe", lat: 60.1706, lng: 24.9440, type: "Fine Art", description: "Finland's most visited art museum with the largest collection of Finnish art and classic European works.", website: "https://ateneum.fi" },

  // Portugal
  { id: "museu-arte-antiga", name: "Museu Nacional de Arte Antiga", city: "Lisbon", country: "Portugal", continent: "Europe", lat: 38.7036, lng: -9.1630, type: "Fine Art", description: "Portugal's most important art museum with European painting, sculpture, and decorative arts from the 14th to 19th century.", website: "https://www.museudearteantiga.pt" },
  { id: "gulbenkian", name: "Museu Calouste Gulbenkian", city: "Lisbon", country: "Portugal", continent: "Europe", lat: 38.7365, lng: -9.1534, type: "Fine Art", description: "An outstanding private collection spanning Egyptian art to Impressionism in beautiful grounds.", website: "https://gulbenkian.pt/museu" },

  // Czech Republic & Poland
  { id: "national-gallery-prague", name: "National Gallery Prague", city: "Prague", country: "Czech Republic", continent: "Europe", lat: 50.0903, lng: 14.3985, type: "Fine Art", description: "The Czech Republic's primary art institution with collections spanning medieval to contemporary art across multiple venues.", website: "https://www.ngprague.cz" },
  { id: "national-museum-krakow", name: "National Museum in Kraków", city: "Kraków", country: "Poland", continent: "Europe", lat: 50.0604, lng: 19.9230, type: "Fine Art", description: "Poland's premier art museum, home to Leonardo da Vinci's Lady with an Ermine.", website: "https://mnk.pl" },

  // Greece & Turkey
  { id: "acropolis-museum", name: "Acropolis Museum", city: "Athens", country: "Greece", continent: "Europe", lat: 37.9684, lng: 23.7285, type: "Fine Art", description: "A stunning modern museum at the foot of the Acropolis housing ancient Greek sculptures and artifacts.", website: "https://www.theacropolismuseum.gr" },
  { id: "istanbul-modern", name: "Istanbul Modern", city: "Istanbul", country: "Turkey", continent: "Europe", lat: 41.0285, lng: 28.9836, type: "Contemporary", description: "Turkey's first museum of modern and contemporary art, in a Renzo Piano building on the Bosphorus.", website: "https://www.istanbulmodern.org" },

  // === ASIA ===
  // Japan
  { id: "tokyo-national", name: "Tokyo National Museum", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.7189, lng: 139.7765, type: "Encyclopedic", description: "Japan's oldest and largest museum with the most comprehensive collection of Japanese art and Asian antiquities.", website: "https://www.tnm.jp" },
  { id: "mori", name: "Mori Art Museum", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.6604, lng: 139.7292, type: "Contemporary", description: "A leading contemporary art museum atop Roppongi Hills with panoramic views of Tokyo.", website: "https://www.mori.art.museum" },
  { id: "national-art-center-tokyo", name: "The National Art Center, Tokyo", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.6652, lng: 139.7262, type: "Contemporary", description: "Japan's largest exhibition facility in a stunning undulating glass building by Kisho Kurokawa.", website: "https://www.nact.jp" },
  { id: "teamlab-borderless", name: "teamLab Borderless", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.6262, lng: 139.7839, type: "Contemporary", description: "An immersive digital art museum where artworks move freely between rooms, merging and influencing each other.", website: "https://www.teamlab.art" },
  { id: "miho", name: "Miho Museum", city: "Shigaraki", country: "Japan", continent: "Asia", lat: 34.8874, lng: 136.0369, type: "Fine Art", description: "Designed by I.M. Pei, nestled in the mountains with an exquisite collection of Asian and Western antiquities.", website: "https://www.miho.jp" },
  { id: "adachi", name: "Adachi Museum of Art", city: "Yasugi", country: "Japan", continent: "Asia", lat: 35.3917, lng: 133.2169, type: "Fine Art", description: "Famous for its stunning Japanese gardens and collection of modern Japanese paintings.", website: "https://www.adachi-museum.or.jp" },
  { id: "21st-century-kanazawa", name: "21st Century Museum of Contemporary Art", city: "Kanazawa", country: "Japan", continent: "Asia", lat: 36.5607, lng: 136.6588, type: "Contemporary", description: "A circular glass museum known for interactive installations like Leandro Erlich's Swimming Pool.", website: "https://www.kanazawa21.jp" },
  { id: "chichu", name: "Chichu Art Museum", city: "Naoshima", country: "Japan", continent: "Asia", lat: 34.4434, lng: 133.9970, type: "Contemporary", description: "Tadao Ando's underground museum on art island Naoshima, housing Monet, Walter De Maria, and James Turrell.", website: "https://benesse-artsite.jp/en/art/chichu.html" },
  { id: "benesse", name: "Benesse House Museum", city: "Naoshima", country: "Japan", continent: "Asia", lat: 34.4393, lng: 133.9981, type: "Contemporary", description: "A unique fusion of museum and hotel by Tadao Ando where art is displayed throughout the building and landscape.", website: "https://benesse-artsite.jp/en/art/benessehouse-museum.html" },

  // China
  { id: "national-museum-china", name: "National Museum of China", city: "Beijing", country: "China", continent: "Asia", lat: 39.9042, lng: 116.3912, type: "Encyclopedic", description: "One of the largest museums in the world, chronicling Chinese art and history across 5,000 years.", website: "https://www.chnmuseum.cn" },
  { id: "palace-museum", name: "Palace Museum (Forbidden City)", city: "Beijing", country: "China", continent: "Asia", lat: 39.9163, lng: 116.3972, type: "Encyclopedic", description: "Set within the Forbidden City, housing an immense collection of Chinese art and imperial treasures.", website: "https://www.dpm.org.cn" },
  { id: "shanghai-museum", name: "Shanghai Museum", city: "Shanghai", country: "China", continent: "Asia", lat: 31.2286, lng: 121.4745, type: "Fine Art", description: "A leading museum of ancient Chinese art, particularly renowned for its bronzes, ceramics, and calligraphy.", website: "https://www.shanghaimuseum.net" },
  { id: "m-plus", name: "M+", city: "Hong Kong", country: "China", continent: "Asia", lat: 22.3022, lng: 114.1600, type: "Contemporary", description: "Asia's first global museum of contemporary visual culture, housing over 48,000 works.", website: "https://www.mplus.org.hk" },
  { id: "ucca", name: "UCCA Center for Contemporary Art", city: "Beijing", country: "China", continent: "Asia", lat: 39.9854, lng: 116.4949, type: "Contemporary", description: "China's leading contemporary art institution, founded in the 798 Art District.", website: "https://ucca.org.cn" },
  { id: "national-palace-taipei", name: "National Palace Museum", city: "Taipei", country: "Taiwan", continent: "Asia", lat: 25.1024, lng: 121.5485, type: "Encyclopedic", description: "Houses one of the world's largest collections of Chinese art and artifacts, nearly 700,000 pieces.", website: "https://www.npm.gov.tw" },

  // South Korea
  { id: "national-museum-korea", name: "National Museum of Korea", city: "Seoul", country: "South Korea", continent: "Asia", lat: 37.5240, lng: 126.9804, type: "Encyclopedic", description: "Korea's largest museum with extensive Korean art, archaeology, and history collections.", website: "https://www.museum.go.kr" },
  { id: "leeum", name: "Leeum Museum of Art", city: "Seoul", country: "South Korea", continent: "Asia", lat: 37.5383, lng: 126.9999, type: "Fine Art", description: "Samsung's art museum with buildings by Mario Botta, Jean Nouvel, and Rem Koolhaas housing Korean and contemporary art.", website: "https://www.leeum.org" },

  // India
  { id: "national-museum-india", name: "National Museum, New Delhi", city: "New Delhi", country: "India", continent: "Asia", lat: 28.6117, lng: 77.2195, type: "Encyclopedic", description: "India's premier cultural institution with over 200,000 works spanning 5,000 years of Indian art and heritage.", website: "https://www.nationalmuseumindia.gov.in" },
  { id: "chhatrapati-shivaji", name: "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", city: "Mumbai", country: "India", continent: "Asia", lat: 18.9268, lng: 72.8326, type: "Encyclopedic", description: "Mumbai's main museum with art, archaeology, and natural history in a stunning Indo-Saracenic building.", website: "https://www.csmvs.in" },

  // Southeast Asia
  { id: "national-gallery-singapore", name: "National Gallery Singapore", city: "Singapore", country: "Singapore", continent: "Asia", lat: 1.2903, lng: 103.8515, type: "Fine Art", description: "The world's largest public collection of Singaporean and Southeast Asian modern art in two restored heritage buildings.", website: "https://www.nationalgallery.sg" },
  { id: "bangkok-art-biennale", name: "Bangkok Art and Culture Centre", city: "Bangkok", country: "Thailand", continent: "Asia", lat: 13.7466, lng: 100.5303, type: "Contemporary", description: "Bangkok's premier contemporary art center hosting rotating exhibitions and cultural events.", website: "https://www.bacc.or.th" },

  // Middle East
  { id: "louvre-abu-dhabi", name: "Louvre Abu Dhabi", city: "Abu Dhabi", country: "United Arab Emirates", continent: "Asia", lat: 24.5338, lng: 54.3984, type: "Encyclopedic", description: "A universal museum under Jean Nouvel's iconic dome, bridging Eastern and Western art traditions.", website: "https://www.louvreabudhabi.ae" },
  { id: "museum-islamic-art", name: "Museum of Islamic Art", city: "Doha", country: "Qatar", continent: "Asia", lat: 25.2958, lng: 51.5395, type: "Fine Art", description: "I.M. Pei's masterwork housing one of the world's most comprehensive collections of Islamic art.", website: "https://mia.org.qa" },
  { id: "israel-museum", name: "Israel Museum", city: "Jerusalem", country: "Israel", continent: "Asia", lat: 31.7727, lng: 35.2043, type: "Encyclopedic", description: "Israel's national museum with the Dead Sea Scrolls, archaeology, fine art, and a renowned sculpture garden.", website: "https://www.imj.org.il" },
  { id: "tel-aviv-museum", name: "Tel Aviv Museum of Art", city: "Tel Aviv", country: "Israel", continent: "Asia", lat: 32.0774, lng: 34.7869, type: "Fine Art", description: "Israel's leading contemporary and modern art museum with strong Impressionist and Israeli collections.", website: "https://www.tamuseum.org.il" },
  { id: "tehran-museum", name: "Tehran Museum of Contemporary Art", city: "Tehran", country: "Iran", continent: "Asia", lat: 35.7147, lng: 51.4079, type: "Contemporary", description: "Houses one of the most valuable collections of Western modern art outside Europe and the US.", website: "https://www.tmoca.com" },

  // === SOUTH AMERICA ===
  { id: "masp", name: "São Paulo Museum of Art (MASP)", city: "São Paulo", country: "Brazil", continent: "South America", lat: -23.5614, lng: -46.6558, type: "Fine Art", description: "Latin America's most important European art collection in Lina Bo Bardi's iconic suspended building.", website: "https://masp.org.br" },
  { id: "pinacoteca-sp", name: "Pinacoteca do Estado de São Paulo", city: "São Paulo", country: "Brazil", continent: "South America", lat: -23.5342, lng: -46.6337, type: "Fine Art", description: "São Paulo's oldest museum dedicated to Brazilian art from the 19th century to present.", website: "https://pinacoteca.org.br" },
  { id: "inhotim", name: "Instituto Inhotim", city: "Brumadinho", country: "Brazil", continent: "South America", lat: -20.1206, lng: -44.2198, type: "Contemporary", description: "The world's largest open-air contemporary art museum set across stunning botanical gardens.", website: "https://www.inhotim.org.br" },
  { id: "malba", name: "MALBA – Museo de Arte Latinoamericano de Buenos Aires", city: "Buenos Aires", country: "Argentina", continent: "South America", lat: -34.5874, lng: -58.4030, type: "Modern Art", description: "Dedicated to Latin American art from the early 20th century to present, including Frida Kahlo and Diego Rivera.", website: "https://www.malba.org.ar" },
  { id: "museo-bellas-artes-ba", name: "Museo Nacional de Bellas Artes", city: "Buenos Aires", country: "Argentina", continent: "South America", lat: -34.5837, lng: -58.3936, type: "Fine Art", description: "Argentina's premier fine arts museum with the most important public collection of art in Latin America.", website: "https://www.bellasartes.gob.ar" },
  { id: "museo-arte-lima", name: "Museo de Arte de Lima (MALI)", city: "Lima", country: "Peru", continent: "South America", lat: -12.0621, lng: -77.0357, type: "Fine Art", description: "Peru's foremost art museum spanning 3,000 years of art from pre-Columbian to contemporary.", website: "https://www.mali.pe" },
  { id: "museo-botero", name: "Museo Botero", city: "Bogotá", country: "Colombia", continent: "South America", lat: 4.5969, lng: -74.0727, type: "Fine Art", description: "Free museum housing Fernando Botero's donation of 208 works including pieces by Picasso, Dalí, and Monet.", website: "https://www.banrepcultural.org/bogota/museo-botero" },
  { id: "museo-bellas-artes-santiago", name: "Museo Nacional de Bellas Artes", city: "Santiago", country: "Chile", continent: "South America", lat: -33.4380, lng: -70.6437, type: "Fine Art", description: "Chile's oldest museum with a collection spanning colonial to contemporary Chilean and international art.", website: "https://www.mnba.gob.cl" },

  // === AFRICA ===
  { id: "zeitz-mocaa", name: "Zeitz Museum of Contemporary Art Africa", city: "Cape Town", country: "South Africa", continent: "Africa", lat: -33.9083, lng: 18.4178, type: "Contemporary", description: "The largest museum of contemporary African art, housed in a converted grain silo at the V&A Waterfront.", website: "https://www.zeitzmocaa.museum" },
  { id: "iziko-south-african-gallery", name: "Iziko South African National Gallery", city: "Cape Town", country: "South Africa", continent: "Africa", lat: -33.9282, lng: 18.4163, type: "Fine Art", description: "South Africa's premier art museum with significant collections of South African, African, and European art.", website: "https://www.iziko.org.za/museums/south-african-national-gallery" },
  { id: "egyptian-museum", name: "Grand Egyptian Museum", city: "Cairo", country: "Egypt", continent: "Africa", lat: 29.9946, lng: 31.1177, type: "Encyclopedic", description: "The world's largest archaeological museum dedicated to a single civilization, near the Giza Pyramids.", website: "https://grandegyptianmuseum.org" },
  { id: "museum-african-art", name: "Museum of African Contemporary Art Al Maaden", city: "Marrakech", country: "Morocco", continent: "Africa", lat: 31.6015, lng: -8.0701, type: "Contemporary", description: "A leading contemporary African art museum in Marrakech promoting dialogue through art.", website: "https://www.macaal.org" },
  { id: "national-museum-african-art", name: "Smithsonian National Museum of African Art", city: "Washington, D.C.", country: "United States", continent: "North America", lat: 38.8882, lng: -77.0231, type: "Fine Art", description: "The only US museum dedicated exclusively to the collection, exhibition, and study of African art.", website: "https://africa.si.edu" },

  // === OCEANIA ===
  { id: "ngv", name: "National Gallery of Victoria", city: "Melbourne", country: "Australia", continent: "Oceania", lat: -37.8226, lng: 144.9689, type: "Encyclopedic", description: "Australia's oldest and largest art museum with an encyclopedic collection spanning international and Australian art.", website: "https://www.ngv.vic.gov.au" },
  { id: "agnsw", name: "Art Gallery of New South Wales", city: "Sydney", country: "Australia", continent: "Oceania", lat: -33.8688, lng: 151.2173, type: "Fine Art", description: "One of Australia's leading art museums with a major expansion and collections spanning Australian to Asian art.", website: "https://www.artgallery.nsw.gov.au" },
  { id: "mona", name: "Museum of Old and New Art (MONA)", city: "Hobart", country: "Australia", continent: "Oceania", lat: -42.8302, lng: 147.2583, type: "Contemporary", description: "A subterranean museum described as a 'subversive adult Disneyland' with provocative and immersive art.", website: "https://mona.net.au" },
  { id: "qagoma", name: "Queensland Art Gallery / Gallery of Modern Art", city: "Brisbane", country: "Australia", continent: "Oceania", lat: -27.4710, lng: 153.0163, type: "Modern Art", description: "Two galleries on the South Bank featuring Australian, Asian, and Pacific art, host of the Asia Pacific Triennial.", website: "https://www.qagoma.qld.gov.au" },
  { id: "te-papa", name: "Te Papa Tongarewa", city: "Wellington", country: "New Zealand", continent: "Oceania", lat: -41.2901, lng: 174.7822, type: "Encyclopedic", description: "New Zealand's national museum blending art, culture, and natural history with a focus on Māori and Pacific collections.", website: "https://www.tepapa.govt.nz" },
  { id: "auckland-art-gallery", name: "Auckland Art Gallery Toi o Tāmaki", city: "Auckland", country: "New Zealand", continent: "Oceania", lat: -36.8520, lng: 174.7643, type: "Fine Art", description: "New Zealand's largest art gallery with an outstanding collection of New Zealand and international art.", website: "https://www.aucklandartgallery.com" },

  // Additional notable museums
  { id: "museo-frida-kahlo", name: "Museo Frida Kahlo (Casa Azul)", city: "Mexico City", country: "Mexico", continent: "North America", lat: 19.3553, lng: -99.1626, type: "Fine Art", description: "The iconic Blue House where Frida Kahlo was born, lived, and died, now a museum dedicated to her life and work.", website: "https://www.museofridakahlo.org.mx" },
  { id: "dia-beacon", name: "Dia:Beacon", city: "Beacon", country: "United States", continent: "North America", lat: 41.5037, lng: -73.9696, type: "Contemporary", description: "A vast contemporary art museum in a former factory presenting major installations from the 1960s to present.", website: "https://www.diaart.org/visit/visit-our-locations-702/702" },
  { id: "mass-moca", name: "Massachusetts Museum of Contemporary Art (MASS MoCA)", city: "North Adams", country: "United States", continent: "North America", lat: 42.7010, lng: -73.1118, type: "Contemporary", description: "One of the largest contemporary art museums in the US, set in a converted factory complex.", website: "https://massmoca.org" },
  { id: "crystal-bridges", name: "Crystal Bridges Museum of American Art", city: "Bentonville", country: "United States", continent: "North America", lat: 36.3826, lng: -94.2028, type: "Fine Art", description: "Moshe Safdie-designed museum set in nature, housing American art from colonial to contemporary, free admission.", website: "https://crystalbridges.org" },
  { id: "dma", name: "Dallas Museum of Art", city: "Dallas", country: "United States", continent: "North America", lat: 32.7876, lng: -96.8010, type: "Encyclopedic", description: "A major encyclopedic museum with a global collection spanning 5,000 years, free general admission.", website: "https://www.dma.org" },
  { id: "cincinnati-art", name: "Cincinnati Art Museum", city: "Cincinnati", country: "United States", continent: "North America", lat: 39.1141, lng: -84.4975, type: "Encyclopedic", description: "One of the oldest art museums in the US with over 67,000 works spanning 6,000 years, free admission.", website: "https://www.cincinnatiartmuseum.org" },
  { id: "telfair", name: "Telfair Museums", city: "Savannah", country: "United States", continent: "North America", lat: 32.0779, lng: -81.0979, type: "Fine Art", description: "The oldest public art museum in the South, combining historic architecture with American and European art.", website: "https://www.telfair.org" },
  { id: "hammer", name: "Hammer Museum", city: "Los Angeles", country: "United States", continent: "North America", lat: 34.0594, lng: -118.4437, type: "Contemporary", description: "A free contemporary art museum affiliated with UCLA, known for cutting-edge exhibitions.", website: "https://hammer.ucla.edu" },
  { id: "portland-art", name: "Portland Art Museum", city: "Portland", country: "United States", continent: "North America", lat: 45.5161, lng: -122.6834, type: "Encyclopedic", description: "The oldest art museum in the Pacific Northwest with significant Native American and Asian collections.", website: "https://portlandartmuseum.org" },
  { id: "seattle-art", name: "Seattle Art Museum", city: "Seattle", country: "United States", continent: "North America", lat: 47.6073, lng: -122.3381, type: "Encyclopedic", description: "A major art museum with Native American, Asian, and contemporary art collections.", website: "https://www.seattleartmuseum.org" },
  { id: "fondation-vuitton", name: "Fondation Louis Vuitton", city: "Paris", country: "France", continent: "Europe", lat: 48.8766, lng: 2.2652, type: "Contemporary", description: "Frank Gehry's spectacular glass building housing a major contemporary art collection and blockbuster exhibitions.", website: "https://www.fondationlouisvuitton.fr" },
  { id: "bourse-commerce", name: "Bourse de Commerce — Pinault Collection", city: "Paris", country: "France", continent: "Europe", lat: 48.8624, lng: 2.3428, type: "Contemporary", description: "François Pinault's contemporary art collection displayed in a historic circular building renovated by Tadao Ando.", website: "https://www.boursedecommerce.fr" },
  { id: "musee-marmottan", name: "Musée Marmottan Monet", city: "Paris", country: "France", continent: "Europe", lat: 48.8601, lng: 2.2669, type: "Fine Art", description: "Home to the world's largest collection of Monet paintings, including Impression, Sunrise that gave Impressionism its name.", website: "https://www.marmottan.fr" },
  { id: "serpentine", name: "Serpentine Galleries", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.5050, lng: -0.1748, type: "Contemporary", description: "Two galleries in Kensington Gardens known for cutting-edge contemporary art and the annual Pavilion commission.", website: "https://www.serpentinegalleries.org" },
  { id: "saatchi", name: "Saatchi Gallery", city: "London", country: "United Kingdom", continent: "Europe", lat: 51.4907, lng: -0.1574, type: "Contemporary", description: "A gallery dedicated to contemporary art, famous for launching the careers of Young British Artists.", website: "https://www.saatchigallery.com" },
  { id: "palazzo-grassi", name: "Palazzo Grassi", city: "Venice", country: "Italy", continent: "Europe", lat: 45.4318, lng: 12.3310, type: "Contemporary", description: "François Pinault's Venice venue for contemporary art in a neoclassical palazzo on the Grand Canal.", website: "https://www.palazzograssi.it" },
  { id: "punta-della-dogana", name: "Punta della Dogana", city: "Venice", country: "Italy", continent: "Europe", lat: 45.4308, lng: 12.3347, type: "Contemporary", description: "A triangular former customs building renovated by Tadao Ando for the Pinault Collection's contemporary art.", website: "https://www.palazzograssi.it/en/about/punta-della-dogana" },
  { id: "museo-arte-moderna-roma", name: "Galleria Nazionale d'Arte Moderna e Contemporanea", city: "Rome", country: "Italy", continent: "Europe", lat: 41.9165, lng: 12.4822, type: "Modern Art", description: "Italy's largest collection of modern and contemporary art, from Neoclassicism to present.", website: "https://lagallerianazionale.com" },
  { id: "maxxi", name: "MAXXI – National Museum of 21st Century Arts", city: "Rome", country: "Italy", continent: "Europe", lat: 41.9281, lng: 12.4665, type: "Contemporary", description: "Zaha Hadid's award-winning building housing Italy's national museum of contemporary art and architecture.", website: "https://www.maxxi.art" },
  { id: "museo-900", name: "Museo del Novecento", city: "Milan", country: "Italy", continent: "Europe", lat: 45.4636, lng: 9.1889, type: "Modern Art", description: "Overlooking the Duomo, dedicated to 20th-century Italian art with works by Fontana, Boccioni, and Morandi.", website: "https://www.museodelnovecento.org" },
  { id: "kiasma", name: "Kiasma – Museum of Contemporary Art", city: "Helsinki", country: "Finland", continent: "Europe", lat: 60.1722, lng: 24.9373, type: "Contemporary", description: "Steven Holl's striking museum showcasing Finnish and international contemporary art.", website: "https://www.kiasma.fi" },
  { id: "arken", name: "ARKEN Museum of Modern Art", city: "Ishøj", country: "Denmark", continent: "Europe", lat: 55.6293, lng: 12.3577, type: "Modern Art", description: "A ship-like building on the coast featuring Nordic and international contemporary art.", website: "https://www.arken.dk" },

  // More Asian museums
  { id: "national-museum-tokyo-modern", name: "The National Museum of Modern Art, Tokyo (MOMAT)", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.6912, lng: 139.7544, type: "Modern Art", description: "Japan's first national art museum with the largest collection of modern Japanese art.", website: "https://www.momat.go.jp" },
  { id: "nezu", name: "Nezu Museum", city: "Tokyo", country: "Japan", continent: "Asia", lat: 35.6622, lng: 139.7190, type: "Fine Art", description: "A tranquil museum with pre-modern Japanese and East Asian art set in beautiful gardens designed by Kengo Kuma.", website: "https://www.nezu-muse.or.jp" },
  { id: "samsung-art", name: "Samsung Museum of Art (Leeum)", city: "Seoul", country: "South Korea", continent: "Asia", lat: 37.5383, lng: 127.0000, type: "Fine Art", description: "South Korea's premier private museum with traditional Korean and international contemporary art.", website: "https://www.leeum.org" },
  { id: "power-station-art", name: "Power Station of Art", city: "Shanghai", country: "China", continent: "Asia", lat: 31.1856, lng: 121.4913, type: "Contemporary", description: "China's first state-run contemporary art museum, host of the Shanghai Biennale.", website: "https://www.powerstationofart.com" },

  // A few more to round out coverage
  { id: "mucem", name: "Mucem", city: "Marseille", country: "France", continent: "Europe", lat: 43.2969, lng: 5.3607, type: "Encyclopedic", description: "Museum of European and Mediterranean Civilisations in a striking latticed-concrete cube by the old port.", website: "https://www.mucem.org" },
  { id: "museo-reina-sofia-cristal", name: "Palacio de Cristal (Reina Sofía)", city: "Madrid", country: "Spain", continent: "Europe", lat: 40.4136, lng: -3.6830, type: "Contemporary", description: "A stunning 19th-century glass pavilion in Retiro Park used for contemporary art installations by Museo Reina Sofía.", website: "https://www.museoreinasofia.es" },
  { id: "van-abbe", name: "Van Abbemuseum", city: "Eindhoven", country: "Netherlands", continent: "Europe", lat: 51.4360, lng: 5.4786, type: "Modern Art", description: "One of Europe's leading museums of modern and contemporary art with works by Picasso, Kandinsky, and El Lissitzky.", website: "https://vanabbemuseum.nl" },
  { id: "museum-berggruen", name: "Museum Berggruen", city: "Berlin", country: "Germany", continent: "Europe", lat: 52.5196, lng: 13.2955, type: "Modern Art", description: "An intimate museum showcasing works by Picasso, Klee, Matisse, and Giacometti.", website: "https://www.smb.museum/en/museums-institutions/museum-berggruen" },
  { id: "kunsthalle-hamburg", name: "Hamburger Kunsthalle", city: "Hamburg", country: "Germany", continent: "Europe", lat: 53.5534, lng: 10.0048, type: "Fine Art", description: "One of the largest and most important art museums in Germany spanning medieval to contemporary art.", website: "https://www.hamburger-kunsthalle.de" },
  { id: "benaki", name: "Benaki Museum", city: "Athens", country: "Greece", continent: "Europe", lat: 37.9751, lng: 23.7416, type: "Encyclopedic", description: "Greece's oldest private museum spanning Greek culture from prehistory to the 20th century.", website: "https://www.benaki.org" },
  { id: "museum-applied-arts-vienna", name: "MAK – Museum of Applied Arts", city: "Vienna", country: "Austria", continent: "Europe", lat: 48.2079, lng: 16.3817, type: "Fine Art", description: "One of the most important museums of applied arts worldwide with Klimt's Stoclet Frieze designs.", website: "https://www.mak.at" }
];
